### ISSUE TITLE
OurDB-Database with read-design in README.md?

### ISSUE THREAD

**Issue by codehangen** [zeelsheladiya/OurDB-Database#6]
Hi all.

#### 1. Idea
I would like to send my first read-design commit, that is to improve the visual aspect of the main file: README.md - where people will read general information from OurDB. Please, see this: [OurDB-readme.md](https://gist.github.com/codehangen/723af9e7ff0e61c9d8f4043e2e55f021)

#### 1.1 img 1 *before*
![image](https://user-images.githubusercontent.com/111701513/209458667-1b21aadf-807d-467a-a1f8-fa6ddf401aae.png)

#### 1.2 img 2 *after*
![image](https://user-images.githubusercontent.com/111701513/209458655-72b7afd1-3865-4f26-b04d-e61b756b012a.png)

#### 2. why?
1. It's an early commit
2. I would just like to improve the visual aspect of a part of the readme.md file
3. > "-> do not commit direct any new update first contact with author than they will test your module and they will commit." 
   - I want to know if this idea is good or bad before I submit an initial PR.

#### 3. question/feedback
What do you all think of the idea?

**Comment by zeelsheladiya** [comment]
thanks for your suggestions. Now I changed the logo as you said to improve visuals. 👍
