### ISSUE TITLE
enable GitHub discussions in this repo: OurDB-Database?

### ISSUE THREAD

**Issue by ghost** [zeelsheladiya/OurDB-Database#8]
Hi,

I would like to contribute to this open source repository, mainly because I believe in this database and use it in some applications.

About this, I would like to help possible users, developers and companies of OurDB if you have questions. To achieve this goal, I hope to answer questions directly through GitHub Discussions.

e.g
![image](https://github.com/zeelsheladiya/OurDB-Database/assets/119423239/d9ab0cfd-6679-4458-bb53-0e8571e6fcaf)

*What do you think of this idea?*

**Comment by zeelsheladiya** [comment]
Thank you for your concern on this topic. I enabled the discussions :)
